blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/kaiding-ucb/data_viewer/discussions
    about: Use Discussions for usage questions and ideas that aren't bugs or feature requests.
